apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: successful-workflow-
  namespace: argo-workflows
spec:
  entrypoint: success-example
  templates:
  - name: success-example
    steps:
    - - name: step-1
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "Starting successful workflow"
    - - name: step-2
        template: calculate
    - - name: step-3
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "Workflow completed successfully!"

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [sh, -c]
      args:
        - |
          echo "{{inputs.parameters.message}}"
          echo "Timestamp: $(date)"

  - name: calculate
    container:
      image: alpine:latest
      command: [sh, -c]
      args:
        - |
          echo "Performing calculation..."
          result=$((42 * 2))
          echo "The answer is: $result"
          sleep 2
          echo "Calculation complete!"